In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
file=pd.read_excel("C:/Users/Administrator/Desktop/Marketing Data Google Ads 6th june.xlsx")

In [36]:
file

Sr no  Impressions       Clicks  Sales Unit  Time Preferred
0   00:00:00        258647   7759.4100   54.315870               1
1   00:30:00        219974   8798.9600   61.592720               1
2   01:00:00          1096     10.9600    0.076720               0
3   01:30:00          1481     14.8100    0.103670               0
4   02:00:00          1794     17.9400    0.125580               0
5   02:30:00          2156     21.5600    0.150920               0
6   03:00:00           413      4.1300    0.028910               0
7   03:30:00           144      1.4400    0.010080               0
8   04:00:00           139      1.3900    0.009730               0
9   04:30:00           191      1.9100    0.013370               0
10  05:00:00           396      3.9600    0.027720               0
11  05:30:00           274      2.7400    0.019180               0
12  06:00:00          3152     31.5200    0.220640               0
13  06:30:00          3089     30.8900    0.216230               0
14  07:00:00          2135     21.3500    0.149450               0
15  07:30:00         18498    369.9600    2.589720               1
16  08:00:00         17843    535.2900    3.747030               1
17  08:30:00         12741    445.9350    3.121545               1
18  09:00:00         18973    683.0280    4.781196               1
19  09:30:00         11746    469.8400    3.288880               1
20  10:00:00         10967    219.3400    1.535380               1
21  10:30:00          8742    419.6160    2.937312               1
22  11:00:00          4059     48.7080    0.340956               0
23  11:30:00         20565    411.3000    2.879100               1
24  12:00:00         24486    710.0940    4.970658               1
25  12:30:00         20491    676.2030    4.733421               1
26  13:00:00        129161   1239.9456    8.679619               1
27  13:30:00        101236   2024.7200   14.173040               1
28  14:00:00        145966   2919.3200   20.435240               1
29  14:30:00         17860    535.8000    3.750600               1
30  15:00:00          1786     53.5800    0.375060               0
31  15:30:00         14741    442.2300    3.095610               1
32  16:00:00         19673    590.1900    4.131330               1
33  16:30:00         12436    422.8240    2.959768               1
34  17:00:00         17491    577.2030    4.040421               1
35  17:30:00         11964    370.8840    2.596188               1
36  18:00:00         22504    720.1280    5.040896               1
37  18:30:00         39613   1980.6500   13.864550               1
38  19:00:00         20654    206.5400    1.445780               1
39  19:30:00         14229    284.5800    1.992060               1
40  20:00:00         11294    112.9400    0.790580               1
41  20:30:00         15977    159.7700    1.118390               1
42  21:00:00         19664    196.6400    1.376480               1
43  21:30:00         19936    239.2320    1.674624               1
44  22:00:00        157866   5525.3100   38.677170               1
45  22:30:00        239844   8154.6960   57.082872               1
46  23:00:00        214526  12871.5600   90.100920               1
47  23:30:00        294484  22969.7520  160.788264               1

In [37]:
file.head()

Sr no  Impressions    Clicks  Sales Unit  Time Preferred
0  00:00:00        258647  7759.41    54.31587               1
1  00:30:00        219974  8798.96    61.59272               1
2  01:00:00          1096    10.96     0.07672               0
3  01:30:00          1481    14.81     0.10367               0
4  02:00:00          1794    17.94     0.12558               0

In [38]:
dataset=file.drop("Sr no",axis=1)

In [39]:
dataset

Impressions       Clicks  Sales Unit  Time Preferred
0         258647   7759.4100   54.315870               1
1         219974   8798.9600   61.592720               1
2           1096     10.9600    0.076720               0
3           1481     14.8100    0.103670               0
4           1794     17.9400    0.125580               0
5           2156     21.5600    0.150920               0
6            413      4.1300    0.028910               0
7            144      1.4400    0.010080               0
8            139      1.3900    0.009730               0
9            191      1.9100    0.013370               0
10           396      3.9600    0.027720               0
11           274      2.7400    0.019180               0
12          3152     31.5200    0.220640               0
13          3089     30.8900    0.216230               0
14          2135     21.3500    0.149450               0
15         18498    369.9600    2.589720               1
16         17843    535.2900    3.747030               1
17         12741    445.9350    3.121545               1
18         18973    683.0280    4.781196               1
19         11746    469.8400    3.288880               1
20         10967    219.3400    1.535380               1
21          8742    419.6160    2.937312               1
22          4059     48.7080    0.340956               0
23         20565    411.3000    2.879100               1
24         24486    710.0940    4.970658               1
25         20491    676.2030    4.733421               1
26        129161   1239.9456    8.679619               1
27        101236   2024.7200   14.173040               1
28        145966   2919.3200   20.435240               1
29         17860    535.8000    3.750600               1
30          1786     53.5800    0.375060               0
31         14741    442.2300    3.095610               1
32         19673    590.1900    4.131330               1
33         12436    422.8240    2.959768               1
34         17491    577.2030    4.040421               1
35         11964    370.8840    2.596188               1
36         22504    720.1280    5.040896               1
37         39613   1980.6500   13.864550               1
38         20654    206.5400    1.445780               1
39         14229    284.5800    1.992060               1
40         11294    112.9400    0.790580               1
41         15977    159.7700    1.118390               1
42         19664    196.6400    1.376480               1
43         19936    239.2320    1.674624               1
44        157866   5525.3100   38.677170               1
45        239844   8154.6960   57.082872               1
46        214526  12871.5600   90.100920               1
47        294484  22969.7520  160.788264               1

In [40]:
dataset.head()

Impressions    Clicks  Sales Unit  Time Preferred
0        258647  7759.41    54.31587               1
1        219974  8798.96    61.59272               1
2          1096    10.96     0.07672               0
3          1481    14.81     0.10367               0
4          1794    17.94     0.12558               0

In [1]:
# discriptive analysis 

In [42]:
dataset.sum()

Impressions       2.207097e+06
Clicks            8.431078e+04
Sales Unit        5.901755e+02
Time Preferred    3.300000e+01
dtype: float64

In [2]:
#Impression are no of visible Ads to customers
#Total Impressions are 2.207097e+06
#Clicks indicates total no of customers who clicked on our Ads
#Total no of Clicks Ad 8.431078e+04

In [3]:
#sales unit indicates total no of purchased made in particular 30 mi of slot
#total no of sales unit for entire day 5.901755e+02

In [4]:
#time preferred is the coloumn which tells us preferred time slot for showing advertisement to the customers

In [46]:
dataset.mean()

Impressions       45981.187500
Clicks             1756.474554
Sales Unit           12.295322
Time Preferred        0.687500
dtype: float64

In [47]:
#the average no of Impression are 45981.187500
#the average no of Clicks are 1756.474554
#the average no of Sales unit are 12.295322

In [48]:
dataset.isnull().sum()

Impressions       0
Clicks            0
Sales Unit        0
Time Preferred    0
dtype: int64

In [49]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [50]:
x

array([[2.58647000e+05, 7.75941000e+03, 5.43158700e+01],
       [2.19974000e+05, 8.79896000e+03, 6.15927200e+01],
       [1.09600000e+03, 1.09600000e+01, 7.67200000e-02],
       [1.48100000e+03, 1.48100000e+01, 1.03670000e-01],
       [1.79400000e+03, 1.79400000e+01, 1.25580000e-01],
       [2.15600000e+03, 2.15600000e+01, 1.50920000e-01],
       [4.13000000e+02, 4.13000000e+00, 2.89100000e-02],
       [1.44000000e+02, 1.44000000e+00, 1.00800000e-02],
       [1.39000000e+02, 1.39000000e+00, 9.73000000e-03],
       [1.91000000e+02, 1.91000000e+00, 1.33700000e-02],
       [3.96000000e+02, 3.96000000e+00, 2.77200000e-02],
       [2.74000000e+02, 2.74000000e+00, 1.91800000e-02],
       [3.15200000e+03, 3.15200000e+01, 2.20640000e-01],
       [3.08900000e+03, 3.08900000e+01, 2.16230000e-01],
       [2.13500000e+03, 2.13500000e+01, 1.49450000e-01],
       [1.84980000e+04, 3.69960000e+02, 2.58972000e+00],
       [1.78430000e+04, 5.35290000e+02, 3.74703000e+00],
       [1.27410000e+04, 4.45935

In [51]:
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int64)

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.05, random_state =0)

In [53]:
print(x_train)

[[1.78600000e+03 5.35800000e+01 3.75060000e-01]
 [1.96730000e+04 5.90190000e+02 4.13133000e+00]
 [3.96130000e+04 1.98065000e+03 1.38645500e+01]
 [1.74910000e+04 5.77203000e+02 4.04042100e+00]
 [1.12940000e+04 1.12940000e+02 7.90580000e-01]
 [1.44000000e+02 1.44000000e+00 1.00800000e-02]
 [3.96000000e+02 3.96000000e+00 2.77200000e-02]
 [2.74000000e+02 2.74000000e+00 1.91800000e-02]
 [1.47410000e+04 4.42230000e+02 3.09561000e+00]
 [1.24360000e+04 4.22824000e+02 2.95976800e+00]
 [1.01236000e+05 2.02472000e+03 1.41730400e+01]
 [2.94484000e+05 2.29697520e+04 1.60788264e+02]
 [1.09600000e+03 1.09600000e+01 7.67200000e-02]
 [2.14526000e+05 1.28715600e+04 9.01009200e+01]
 [1.89730000e+04 6.83028000e+02 4.78119600e+00]
 [1.84980000e+04 3.69960000e+02 2.58972000e+00]
 [1.45966000e+05 2.91932000e+03 2.04352400e+01]
 [4.05900000e+03 4.87080000e+01 3.40956000e-01]
 [1.78430000e+04 5.35290000e+02 3.74703000e+00]
 [1.59770000e+04 1.59770000e+02 1.11839000e+00]
 [1.09670000e+04 2.19340000e+02 1.535380

In [54]:
print(y_train)

[0 1 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 0 1 1
 1 1 0 1 1 0 1 1]


In [55]:
print(x_test)

[[1.7860000e+04 5.3580000e+02 3.7506000e+00]
 [1.7940000e+03 1.7940000e+01 1.2558000e-01]
 [1.2916100e+05 1.2399456e+03 8.6796192e+00]]


In [56]:
print(y_test)

[1 0 1]


In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [58]:
print(x_train)

[[-0.56125976 -0.42277215 -0.42277215]
 [-0.33285405 -0.29533013 -0.29533013]
 [-0.07823282  0.03489671  0.03489671]
 [-0.36071681 -0.29841448 -0.29841448]
 [-0.4398486  -0.40867447 -0.40867447]
 [-0.58222707 -0.43515512 -0.43515512]
 [-0.57900918 -0.43455663 -0.43455663]
 [-0.58056705 -0.43484638 -0.43484638]
 [-0.39583258 -0.33046984 -0.33046984]
 [-0.42526598 -0.33507867 -0.33507867]
 [ 0.70865404  0.0453631   0.0453631 ]
 [ 3.17630916  5.01969665  5.01969665]
 [-0.57007063 -0.43289417 -0.43289417]
 [ 2.15529591  2.62142983  2.62142983]
 [-0.34179261 -0.2732816  -0.2732816 ]
 [-0.34785806 -0.34763358 -0.34763358]
 [ 1.27982794  0.25782584  0.25782584]
 [-0.53223498 -0.42392922 -0.42392922]
 [-0.35622199 -0.30836859 -0.30836859]
 [-0.38004964 -0.39755259 -0.39755259]
 [-0.44402418 -0.38340503 -0.38340503]
 [-0.33296897 -0.38879616 -0.38879616]
 [-0.58229091 -0.435167   -0.435167  ]
 [-0.54462127 -0.4281609  -0.4281609 ]
 [-0.3224087  -0.2749025  -0.2749025 ]
 [-0.55653509 -0.43037673

In [59]:
print(x_test)

[[-0.35600491 -0.30824747 -0.30824747]
 [-0.56115761 -0.43123646 -0.43123646]
 [ 1.06523868 -0.14101664 -0.14101664]]


In [60]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(random_state=0)

In [61]:
print(classifier.predict(sc.transform([[20491,676.2030,4.733421]])))


[1]


In [62]:
#Conclusion 
#There are 33 no of preferred time slot of 30 min in a entire day where it is preferable to show the Advertisement

In [63]:
#In late night 12 am to 12:30 am,
#In morning 7:30 am to 10:30 am,
#In late morning 11:30 am to 12:00 pm,
#In Early afternoon 12:00 pm to 2:30 pm,
#In Mid afternoon 3:30 pm to 4 pm,
#In Late afternoon 4 pm to 6 pm,
#In Evening 6 pm to 9 pm,
#In Late evening 9 pm to 11:30 pm
#These are the timing where copmany has received the sales

In [64]:
#Using above algorithm we have classify that we have successfully train the data and classified into 2 categerious
#this timing is preferred and not preferred


In [65]:
#In this way we have used decision tree algorithm to classify time slots which are preferable for conversion campaign
#This will help makketing to take decision about remarketing campaign
