In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
file=pd.read_excel("C:/Users/Administrator/Desktop/Google ads hourly analysis 20th june.xlsx")

In [4]:
file

Sr no  Impressions   Clicks  Cost      CTR        CPC  Cold Leads   \
0   00:00:00          9241     554    577  0.0600   1.041516           22   
1   00:30:00          8873     355    498  0.0400   1.402817           14   
2   01:00:00          3956     119    396  0.0300   3.327731            5   
3   01:30:00           956      38     95  0.0400   2.500000            2   
4   02:00:00           548      11     41  0.0200   3.727273            0   
5   02:30:00            62       1     23  0.0200  23.000000            0   
6   03:00:00            48       1     15  0.0200  15.000000            0   
7   03:30:00            36       0      9  0.0120        NaN            0   
8   04:00:00            19       0      7  0.0110        NaN            0   
9   04:30:00            26       0      6  0.0190        NaN            0   
10  05:00:00            45       1      7  0.0140   7.000000            0   
11  05:30:00            59       1     12  0.0200  12.000000            0   
12  06:00:00            36       0      9  0.0020        NaN            0   
13  06:30:00           263       5     14  0.0200   2.800000            0   
14  07:00:00           413       9     18  0.0220   2.000000            0   
15  07:30:00           368      18     36  0.0500   2.000000            1   
16  08:00:00           565      34     49  0.0600   1.441176            1   
17  08:30:00           486      34     63  0.0700   1.852941            1   
18  09:00:00           656      59     81  0.0900   1.372881            2   
19  09:30:00          1025     123    148  0.1200   1.203252            5   
20  10:00:00          1475     192    212  0.1300   1.104167            8   
21  10:30:00          1488      85    180  0.0569   2.117647            3   
22  11:00:00          1965     295    241  0.1500   0.816949           12   
23  11:30:00          2644     317    345  0.1200   1.088328           13   
24  12:00:00          3248     422    256  0.1300   0.606635           17   
25  12:30:00          3965     476    267  0.1200   0.560924           19   
26  13:00:00          4159     582    295  0.1400   0.506873           23   
27  13:30:00          4859     680    286  0.1400   0.420588           27   
28  14:00:00          4723     614    287  0.1300   0.467427           25   
29  14:30:00          5012     702    289  0.1400   0.411681           28   
30  15:00:00          5656     792    287  0.1400   0.362374           32   
31  15:30:00          5648     791    361  0.1400   0.456384           32   
32  16:00:00          4999     700    480  0.1400   0.685714           28   
33  16:30:00          4125    1031    399  0.2500   0.387003           41   
34  17:00:00          5948     952    509  0.1600   0.534664           38   
35  17:30:00          9458    1797    652  0.1900   0.362827           72   
36  18:00:00          9512    1998    641  0.2100   0.320821           80   
37  18:30:00          9477    2180    704  0.2300   0.322936           87   
38  19:00:00          9888    2571    655  0.2600   0.254765          103   
39  19:30:00         10256    2154    945  0.2100   0.438719           86   
40  20:00:00          9489    1423    628  0.1500   0.441321           57   
41  20:30:00          9899    1386    647  0.1400   0.466811           55   
42  21:00:00          9659    1545    632  0.1600   0.409061           62   
43  21:30:00          7845    1177    647  0.1500   0.549703           47   
44  22:00:00          7444    1191    625  0.1600   0.524769           48   
45  22:30:00          8401    1596    947  0.1900   0.593358           64   
46  23:00:00          8955    1522    948  0.1700   0.622865           61   
47  23:30:00          9120    1459    936  0.1600   0.641535           58   

    Warm Leads  Hot Leads  
0           11          2  
1            7          1  
2            3          1  
3            1          0  
4            0          0  
5            0          0  
6            0          0  
7        

In [5]:
file.head()

Sr no  Impressions   Clicks  Cost    CTR       CPC  Cold Leads   \
0  00:00:00          9241     554    577  0.06  1.041516           22   
1  00:30:00          8873     355    498  0.04  1.402817           14   
2  01:00:00          3956     119    396  0.03  3.327731            5   
3  01:30:00           956      38     95  0.04  2.500000            2   
4  02:00:00           548      11     41  0.02  3.727273            0   

   Warm Leads  Hot Leads  
0          11          2  
1           7          1  
2           3          1  
3           1          0  
4           0          0

In [6]:
dataset=file.drop("Sr no",axis=1)

In [7]:
dataset

Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           9241     554    577  0.0600   1.041516           22          11   
1           8873     355    498  0.0400   1.402817           14           7   
2           3956     119    396  0.0300   3.327731            5           3   
3            956      38     95  0.0400   2.500000            2           1   
4            548      11     41  0.0200   3.727273            0           0   
5             62       1     23  0.0200  23.000000            0           0   
6             48       1     15  0.0200  15.000000            0           0   
7             36       0      9  0.0120        NaN            0           0   
8             19       0      7  0.0110        NaN            0           0   
9             26       0      6  0.0190        NaN            0           0   
10            45       1      7  0.0140   7.000000            0           0   
11            59       1     12  0.0200  12.000000            0           0   
12            36       0      9  0.0020        NaN            0           0   
13           263       5     14  0.0200   2.800000            0           0   
14           413       9     18  0.0220   2.000000            0           0   
15           368      18     36  0.0500   2.000000            1           1   
16           565      34     49  0.0600   1.441176            1           1   
17           486      34     63  0.0700   1.852941            1           1   
18           656      59     81  0.0900   1.372881            2           1   
19          1025     123    148  0.1200   1.203252            5           3   
20          1475     192    212  0.1300   1.104167            8           4   
21          1488      85    180  0.0569   2.117647            3           2   
22          1965     295    241  0.1500   0.816949           12           6   
23          2644     317    345  0.1200   1.088328           13           7   
24          3248     422    256  0.1300   0.606635           17           9   
25          3965     476    267  0.1200   0.560924           19          10   
26          4159     582    295  0.1400   0.506873           23          12   
27          4859     680    286  0.1400   0.420588           27          14   
28          4723     614    287  0.1300   0.467427           25          13   
29          5012     702    289  0.1400   0.411681           28          14   
30          5656     792    287  0.1400   0.362374           32          16   
31          5648     791    361  0.1400   0.456384           32          16   
32          4999     700    480  0.1400   0.685714           28          14   
33          4125    1031    399  0.2500   0.387003           41          21   
34          5948     952    509  0.1600   0.534664           38          19   
35          9458    1797    652  0.1900   0.362827           72          36   
36          9512    1998    641  0.2100   0.320821           80          40   
37          9477    2180    704  0.2300   0.322936           87          44   
38          9888    2571    655  0.2600   0.254765          103          52   
39         10256    2154    945  0.2100   0.438719           86          43   
40          9489    1423    628  0.1500   0.441321           57          29   
41          9899    1386    647  0.1400   0.466811           55          28   
42          9659    1545    632  0.1600   0.409061           62          31   
43          7845    1177    647  0.1500   0.549703           47          24   
44          7444    1191    625  0.1600   0.524769           48          24   
45          8401    1596    947  0.1900   0.593358           64          32   
46          8955    1522    948  0.1700   0.622865           61          31   
47          9120    1459    936  0.1600   0.641535           58          29   

    Hot Leads  
0           2  
1           1  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [8]:
a=dataset.isnull().sum()

In [9]:
a

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             4
Cold Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [11]:
dataset1=dataset.fillna(a.mean())

In [13]:
dataset1

Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           9241     554    577  0.0600   1.041516           22          11   
1           8873     355    498  0.0400   1.402817           14           7   
2           3956     119    396  0.0300   3.327731            5           3   
3            956      38     95  0.0400   2.500000            2           1   
4            548      11     41  0.0200   3.727273            0           0   
5             62       1     23  0.0200  23.000000            0           0   
6             48       1     15  0.0200  15.000000            0           0   
7             36       0      9  0.0120   0.500000            0           0   
8             19       0      7  0.0110   0.500000            0           0   
9             26       0      6  0.0190   0.500000            0           0   
10            45       1      7  0.0140   7.000000            0           0   
11            59       1     12  0.0200  12.000000            0           0   
12            36       0      9  0.0020   0.500000            0           0   
13           263       5     14  0.0200   2.800000            0           0   
14           413       9     18  0.0220   2.000000            0           0   
15           368      18     36  0.0500   2.000000            1           1   
16           565      34     49  0.0600   1.441176            1           1   
17           486      34     63  0.0700   1.852941            1           1   
18           656      59     81  0.0900   1.372881            2           1   
19          1025     123    148  0.1200   1.203252            5           3   
20          1475     192    212  0.1300   1.104167            8           4   
21          1488      85    180  0.0569   2.117647            3           2   
22          1965     295    241  0.1500   0.816949           12           6   
23          2644     317    345  0.1200   1.088328           13           7   
24          3248     422    256  0.1300   0.606635           17           9   
25          3965     476    267  0.1200   0.560924           19          10   
26          4159     582    295  0.1400   0.506873           23          12   
27          4859     680    286  0.1400   0.420588           27          14   
28          4723     614    287  0.1300   0.467427           25          13   
29          5012     702    289  0.1400   0.411681           28          14   
30          5656     792    287  0.1400   0.362374           32          16   
31          5648     791    361  0.1400   0.456384           32          16   
32          4999     700    480  0.1400   0.685714           28          14   
33          4125    1031    399  0.2500   0.387003           41          21   
34          5948     952    509  0.1600   0.534664           38          19   
35          9458    1797    652  0.1900   0.362827           72          36   
36          9512    1998    641  0.2100   0.320821           80          40   
37          9477    2180    704  0.2300   0.322936           87          44   
38          9888    2571    655  0.2600   0.254765          103          52   
39         10256    2154    945  0.2100   0.438719           86          43   
40          9489    1423    628  0.1500   0.441321           57          29   
41          9899    1386    647  0.1400   0.466811           55          28   
42          9659    1545    632  0.1600   0.409061           62          31   
43          7845    1177    647  0.1500   0.549703           47          24   
44          7444    1191    625  0.1600   0.524769           48          24   
45          8401    1596    947  0.1900   0.593358           64          32   
46          8955    1522    948  0.1700   0.622865           61          31   
47          9120    1459    936  0.1600   0.641535           58          29   

    Hot Leads  
0           2  
1           1  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [14]:
dataset1.isnull().sum()

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [15]:
dataset1


Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           9241     554    577  0.0600   1.041516           22          11   
1           8873     355    498  0.0400   1.402817           14           7   
2           3956     119    396  0.0300   3.327731            5           3   
3            956      38     95  0.0400   2.500000            2           1   
4            548      11     41  0.0200   3.727273            0           0   
5             62       1     23  0.0200  23.000000            0           0   
6             48       1     15  0.0200  15.000000            0           0   
7             36       0      9  0.0120   0.500000            0           0   
8             19       0      7  0.0110   0.500000            0           0   
9             26       0      6  0.0190   0.500000            0           0   
10            45       1      7  0.0140   7.000000            0           0   
11            59       1     12  0.0200  12.000000            0           0   
12            36       0      9  0.0020   0.500000            0           0   
13           263       5     14  0.0200   2.800000            0           0   
14           413       9     18  0.0220   2.000000            0           0   
15           368      18     36  0.0500   2.000000            1           1   
16           565      34     49  0.0600   1.441176            1           1   
17           486      34     63  0.0700   1.852941            1           1   
18           656      59     81  0.0900   1.372881            2           1   
19          1025     123    148  0.1200   1.203252            5           3   
20          1475     192    212  0.1300   1.104167            8           4   
21          1488      85    180  0.0569   2.117647            3           2   
22          1965     295    241  0.1500   0.816949           12           6   
23          2644     317    345  0.1200   1.088328           13           7   
24          3248     422    256  0.1300   0.606635           17           9   
25          3965     476    267  0.1200   0.560924           19          10   
26          4159     582    295  0.1400   0.506873           23          12   
27          4859     680    286  0.1400   0.420588           27          14   
28          4723     614    287  0.1300   0.467427           25          13   
29          5012     702    289  0.1400   0.411681           28          14   
30          5656     792    287  0.1400   0.362374           32          16   
31          5648     791    361  0.1400   0.456384           32          16   
32          4999     700    480  0.1400   0.685714           28          14   
33          4125    1031    399  0.2500   0.387003           41          21   
34          5948     952    509  0.1600   0.534664           38          19   
35          9458    1797    652  0.1900   0.362827           72          36   
36          9512    1998    641  0.2100   0.320821           80          40   
37          9477    2180    704  0.2300   0.322936           87          44   
38          9888    2571    655  0.2600   0.254765          103          52   
39         10256    2154    945  0.2100   0.438719           86          43   
40          9489    1423    628  0.1500   0.441321           57          29   
41          9899    1386    647  0.1400   0.466811           55          28   
42          9659    1545    632  0.1600   0.409061           62          31   
43          7845    1177    647  0.1500   0.549703           47          24   
44          7444    1191    625  0.1600   0.524769           48          24   
45          8401    1596    947  0.1900   0.593358           64          32   
46          8955    1522    948  0.1700   0.622865           61          31   
47          9120    1459    936  0.1600   0.641535           58          29   

    Hot Leads  
0           2  
1           1  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [16]:
dataset2=dataset1.drop(["CPC","CTR","Warm Leads"],axis=1)

In [17]:
dataset2

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0           9241     554    577           22          2
1           8873     355    498           14          1
2           3956     119    396            5          1
3            956      38     95            2          0
4            548      11     41            0          0
5             62       1     23            0          0
6             48       1     15            0          0
7             36       0      9            0          0
8             19       0      7            0          0
9             26       0      6            0          0
10            45       1      7            0          0
11            59       1     12            0          0
12            36       0      9            0          0
13           263       5     14            0          0
14           413       9     18            0          0
15           368      18     36            1          0
16           565      34     49            1          0
17           486      34     63            1          0
18           656      59     81            2          0
19          1025     123    148            5          1
20          1475     192    212            8          1
21          1488      85    180            3          0
22          1965     295    241           12          1
23          2644     317    345           13          1
24          3248     422    256           17          2
25          3965     476    267           19          2
26          4159     582    295           23          3
27          4859     680    286           27          3
28          4723     614    287           25          3
29          5012     702    289           28          3
30          5656     792    287           32          3
31          5648     791    361           32          3
32          4999     700    480           28          3
33          4125    1031    399           41          4
34          5948     952    509           38          4
35          9458    1797    652           72          8
36          9512    1998    641           80          8
37          9477    2180    704           87          9
38          9888    2571    655          103         11
39         10256    2154    945           86          9
40          9489    1423    628           57          6
41          9899    1386    647           55          6
42          9659    1545    632           62          7
43          7845    1177    647           47          5
44          7444    1191    625           48          5
45          8401    1596    947           64          7
46          8955    1522    948           61          7
47          9120    1459    936           58          6

In [18]:
dataset2.head()

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0          9241     554    577           22          2
1          8873     355    498           14          1
2          3956     119    396            5          1
3           956      38     95            2          0
4           548      11     41            0          0

In [19]:
# descriptive analysis 

In [20]:
dataset1.sum()

Impressions     206998.000000
Clicks           31993.000000
Cost             16405.000000
CTR                  5.206900
CPC                100.146437
Cold Leads        1279.000000
Warm Leads         649.000000
Hot Leads          135.000000
dtype: float64

In [21]:
#Impressions are no of visible ads to customers
#Total impressions are 206998.000000
#Clicks indicates total no of customers who clicked on our ads
#total no of clicks ad 31993.000000


In [22]:
#Cost indicates cost per click and impression for ads
#Total cost are  16405.000000

In [23]:
#CTR indicates the no of clicks that your ad recives divided by the no of times your ad is shown 
#Total CTR is 5.206900

In [24]:
#CPC indicates dividing the ads cost by the number of clicks generated by an ads
#total CPC is 100.146437

In [25]:
#Cold lead indicates those  customers shows only intrest in Ads
#Warm lead indicates those customers are showing intrest in Ads and providing their contact details
#Hot lead indicates those customers are highly intrested and are ready to buy 

In [26]:
#Total no of Cold lead are 1279.000000
#Total no of Warm lead are 649.000000
#Total no of Hot lead are  135.000000

In [27]:
dataset1.mean()

Impressions     4312.458333
Clicks           666.520833
Cost             341.770833
CTR                0.108477
CPC                2.086384
Cold Leads        26.645833
Warm Leads        13.520833
Hot Leads          2.812500
dtype: float64

In [28]:
#the average no of Impression are  4312.458333
#the average no of Clicks are 666.520833
#the average no pf cost is 341.770833
#the average no of CTR is 0.108477
#the average no of CPC is 2.230601
#the average no of cold lead  26.645833 
#the average no of warm lead  13.520833
#the average no of hot lead  2.812500

In [29]:
#Individual ratio
#Individual ratio of cold lead and warm lead is 50%
#Individual ratio of warm lead and hot lead is 18.18%
#Individual ratio of cold lead and hot lead is 9.09%


In [30]:
#On an average ratio
#on an average ratio of cold lead and warm lead is 50.74%
#on an average ratio of warm lead and hot lead is 20.80%
#on an average ratio of cold lead and hot lead is 10.55%

In [31]:
x=dataset2.iloc[:,:-1].values
y=dataset2.iloc[:,-1].values

In [32]:
x

array([[ 9241,   554,   577,    22],
       [ 8873,   355,   498,    14],
       [ 3956,   119,   396,     5],
       [  956,    38,    95,     2],
       [  548,    11,    41,     0],
       [   62,     1,    23,     0],
       [   48,     1,    15,     0],
       [   36,     0,     9,     0],
       [   19,     0,     7,     0],
       [   26,     0,     6,     0],
       [   45,     1,     7,     0],
       [   59,     1,    12,     0],
       [   36,     0,     9,     0],
       [  263,     5,    14,     0],
       [  413,     9,    18,     0],
       [  368,    18,    36,     1],
       [  565,    34,    49,     1],
       [  486,    34,    63,     1],
       [  656,    59,    81,     2],
       [ 1025,   123,   148,     5],
       [ 1475,   192,   212,     8],
       [ 1488,    85,   180,     3],
       [ 1965,   295,   241,    12],
       [ 2644,   317,   345,    13],
       [ 3248,   422,   256,    17],
       [ 3965,   476,   267,    19],
       [ 4159,   582,   295,    23],
 

In [33]:
y

array([ 2,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  0,  1,  1,  2,  2,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  8,  8,  9, 11,  9,  6,  6,  7,  5,  5,  7,  7,  6],
      dtype=int64)

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10, random_state =0)

In [35]:
print(x_train)

[[ 9477  2180   704    87]
 [ 5948   952   509    38]
 [ 9489  1423   628    57]
 [   36     0     9     0]
 [   45     1     7     0]
 [   59     1    12     0]
 [ 5648   791   361    32]
 [ 4125  1031   399    41]
 [ 4859   680   286    27]
 [ 9120  1459   936    58]
 [ 3956   119   396     5]
 [ 8955  1522   948    61]
 [  656    59    81     2]
 [  368    18    36     1]
 [ 4723   614   287    25]
 [ 1965   295   241    12]
 [  565    34    49     1]
 [ 9899  1386   647    55]
 [ 1475   192   212     8]
 [ 9659  1545   632    62]
 [   19     0     7     0]
 [  263     5    14     0]
 [ 3965   476   267    19]
 [   62     1    23     0]
 [  486    34    63     1]
 [ 9458  1797   652    72]
 [  413     9    18     0]
 [ 9888  2571   655   103]
 [ 8873   355   498    14]
 [   36     0     9     0]
 [ 7845  1177   647    47]
 [ 3248   422   256    17]
 [   48     1    15     0]
 [ 2644   317   345    13]
 [ 9512  1998   641    80]
 [ 1488    85   180     3]
 [ 1025   123   148     5]
 

In [36]:
print(y_train)

[ 9  4  6  0  0  0  3  4  3  6  1  7  0  0  3  1  0  6  1  7  0  0  2  0
  0  8  0 11  1  0  5  2  0  1  8  0  1  0  9  7  0  2  5]


In [37]:
print(x_test)

[[5012  702  289   28]
 [ 548   11   41    0]
 [4159  582  295   23]
 [5656  792  287   32]
 [4999  700  480   28]]


In [38]:
print(y_test)

[3 0 3 3 3]


In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [40]:
print(x_train)

[[ 1.32142952e+00  2.00651481e+00  1.16437002e+00  1.99912826e+00]
 [ 4.13621612e-01  3.64713464e-01  5.24534996e-01  3.62065203e-01]
 [ 1.32451643e+00  9.94427170e-01  9.14998419e-01  9.96844755e-01]
 [-1.10719458e+00 -9.08083667e-01 -1.11606762e+00 -9.07493900e-01]
 [-1.10487940e+00 -9.06746696e-01 -1.12263003e+00 -9.07493900e-01]
 [-1.10127801e+00 -9.06746696e-01 -1.10622401e+00 -9.07493900e-01]
 [ 3.36448936e-01  1.49461008e-01  3.89166203e-02  1.61608503e-01]
 [-5.53310137e-02  4.70334234e-01  1.63602419e-01  4.62293553e-01]
 [ 1.33484799e-01  1.05714047e-03 -2.07173773e-01 -5.43874769e-03]
 [ 1.22959404e+00  1.04255815e+00  1.92560963e+00  1.03025420e+00]
 [-9.88049543e-02 -7.48984026e-01  1.53758804e-01 -7.40446649e-01]
 [ 1.18714906e+00  1.12678738e+00  1.96498410e+00  1.13048256e+00]
 [-9.47704387e-01 -8.29202333e-01 -8.79820847e-01 -8.40675000e-01]
 [-1.02179016e+00 -8.84018176e-01 -1.02747508e+00 -8.74084450e-01]
 [ 9.84998531e-02 -8.71829968e-02 -2.03892567e-01 -7.22576478e

In [41]:
print(x_test)

[[ 0.17284286  0.03047052 -0.19733016  0.0279707 ]
 [-0.97548655 -0.89337698 -1.01106906 -0.9074939 ]
 [-0.04658478 -0.12996609 -0.17764293 -0.13907655]
 [ 0.33850687  0.15079798 -0.20389257  0.1616085 ]
 [ 0.16949871  0.02779658  0.42938004  0.0279707 ]]


In [42]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(random_state=0)

In [43]:
print(classifier.predict(sc.transform([[9489,1423,628,57]])))

[6]


In [44]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [0 0]
 [2 3]
 [3 3]
 [4 3]]


In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1 0 0 0]
 [0 0 0 0]
 [0 1 2 1]
 [0 0 0 0]]


0.6

In [46]:
#Accuracy is 60%

In [47]:
#Conclusion 
#There are 31 no of preferred time slot of 30 min in a entire day where it is preferable to show the Advertisement
#In which 5:30 pm to 11:30 pm from evening to night company has generated more no of hot leads so we concluded that
#We can show ads to people in above given time slots as more no of people use their mobile phones in evening and night
#so this time is preferrable.
#The maximum cost we used to show ad is in time slot of 7:30 pm to 11:30 pm where we generate 6,7,8,9,11 no of hot leads
#In each no of time slot
# In the time slots company has get more no of impressions, clicks,cold lead,warm lead,hot lead.

In [48]:
#There are 17 no of non preferred time slots and that company dosent get hot lead

In [49]:
#In time slots where company dosent get hot lead company spent 665 rs 
#In reamaning time slots where company got hot leads company spent 15470 rs
#So total cost spent by  company on every time slot is 16405 rs
#95.94% of cost spent by company make profit by getting HOT Leads.

In [51]:
#We suggest we can reduce the cost by 4.05% not spending in the 1:00 am to 9:00 am time slots