In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
file=pd.read_excel("C:/Users/Administrator/Desktop/Marketing Data Google Ads 4th june.xlsx")

In [3]:
file

Sr no  Impressions    Clicks  Sales Unit  Time preferred
0   00:00:00        245847  245.847     2.45847               1
1   00:30:00        159674  159.674     1.59674               1
2   01:00:00          1896    1.896     0.01896               0
3   01:30:00          1789    1.789     0.01789               0
4   02:00:00          1990    1.990     0.01990               0
5   02:30:00          1299    1.299     0.01299               0
6   03:00:00           180    0.180     0.00180               0
7   03:30:00           189    0.189     0.00189               0
8   04:00:00           175    0.175     0.00175               0
9   04:30:00           183    0.183     0.00183               0
10  05:00:00           596    0.596     0.00596               0
11  05:30:00           574    0.574     0.00574               0
12  06:00:00          1752    1.752     0.01752               0
13  06:30:00          1789    1.789     0.01789               0
14  07:00:00          1235    1.235     0.01235               0
15  07:30:00         15478   15.478     0.15478               0
16  08:00:00         15963   15.963     0.15963               0
17  08:30:00         12258   12.258     0.12258               0
18  09:00:00         18964   18.964     0.18964               0
19  09:30:00         17846   17.846     0.17846               0
20  10:00:00         10253   10.253     0.10253               0
21  10:30:00          9452    9.452     0.09452               0
22  11:00:00          4858    4.858     0.04858               0
23  11:30:00         19645   19.645     0.19645               0
24  12:00:00         16486   16.486     0.16486               0
25  12:30:00         18452   18.452     0.18452               0
26  13:00:00        120456  120.456     1.20456               1
27  13:30:00        102396  102.396     1.02396               1
28  14:00:00        158476  158.476     1.58476               1
29  14:30:00         14200   14.200     0.14200               0
30  15:00:00         15207   15.207     0.15207               0
31  15:30:00         12784   12.784     0.12784               0
32  16:00:00         16347   16.347     0.16347               0
33  16:30:00         12363   12.363     0.12363               0
34  17:00:00         13331   13.331     0.13331               0
35  17:30:00         19634   19.634     0.19634               0
36  18:00:00         20486   20.486     0.20486               0
37  18:30:00         32146   32.146     0.32146               0
38  19:00:00         17546   17.546     0.17546               0
39  19:30:00         10242   10.242     0.10242               0
40  20:00:00         10694   10.694     0.10694               0
41  20:30:00         14786   14.786     0.14786               0
42  21:00:00         15966   15.966     0.15966               0
43  21:30:00         19996   19.996     0.19996               0
44  22:00:00        147896  147.896     1.47896               1
45  22:30:00        207894  207.894     2.07894               1
46  23:00:00        210006  210.006     2.10006               1
47  23:30:00        254964  254.964     2.54964               1

In [4]:
file.head()

Sr no  Impressions    Clicks  Sales Unit  Time preferred
0  00:00:00        245847  245.847     2.45847               1
1  00:30:00        159674  159.674     1.59674               1
2  01:00:00          1896    1.896     0.01896               0
3  01:30:00          1789    1.789     0.01789               0
4  02:00:00          1990    1.990     0.01990               0

In [5]:
dataset=file.drop("Sr no",axis=1)

In [6]:
dataset

Impressions    Clicks  Sales Unit  Time preferred
0         245847  245.847     2.45847               1
1         159674  159.674     1.59674               1
2           1896    1.896     0.01896               0
3           1789    1.789     0.01789               0
4           1990    1.990     0.01990               0
5           1299    1.299     0.01299               0
6            180    0.180     0.00180               0
7            189    0.189     0.00189               0
8            175    0.175     0.00175               0
9            183    0.183     0.00183               0
10           596    0.596     0.00596               0
11           574    0.574     0.00574               0
12          1752    1.752     0.01752               0
13          1789    1.789     0.01789               0
14          1235    1.235     0.01235               0
15         15478   15.478     0.15478               0
16         15963   15.963     0.15963               0
17         12258   12.258     0.12258               0
18         18964   18.964     0.18964               0
19         17846   17.846     0.17846               0
20         10253   10.253     0.10253               0
21          9452    9.452     0.09452               0
22          4858    4.858     0.04858               0
23         19645   19.645     0.19645               0
24         16486   16.486     0.16486               0
25         18452   18.452     0.18452               0
26        120456  120.456     1.20456               1
27        102396  102.396     1.02396               1
28        158476  158.476     1.58476               1
29         14200   14.200     0.14200               0
30         15207   15.207     0.15207               0
31         12784   12.784     0.12784               0
32         16347   16.347     0.16347               0
33         12363   12.363     0.12363               0
34         13331   13.331     0.13331               0
35         19634   19.634     0.19634               0
36         20486   20.486     0.20486               0
37         32146   32.146     0.32146               0
38         17546   17.546     0.17546               0
39         10242   10.242     0.10242               0
40         10694   10.694     0.10694               0
41         14786   14.786     0.14786               0
42         15966   15.966     0.15966               0
43         19996   19.996     0.19996               0
44        147896  147.896     1.47896               1
45        207894  207.894     2.07894               1
46        210006  210.006     2.10006               1
47        254964  254.964     2.54964               1

In [7]:
dataset.head()

Impressions    Clicks  Sales Unit  Time preferred
0        245847  245.847     2.45847               1
1        159674  159.674     1.59674               1
2          1896    1.896     0.01896               0
3          1789    1.789     0.01789               0
4          1990    1.990     0.01990               0

In [8]:
# descriptive analysis 

In [9]:
dataset.sum()

Impressions       2.026639e+06
Clicks            2.026639e+03
Sales Unit        2.026639e+01
Time preferred    9.000000e+00
dtype: float64

In [10]:
#Impressions are no of visible ads to customers
#Total impressions are  2.026639e+06
#Clicks indicates total no of customers who clicked on our ads
#total no of clicks ad 2.026639e+03


In [11]:
#sales unit indicates total no of purchased made in particular 30 mi of slot
#total no of sales unit for entire day 2.026639e+01

In [12]:
#time preferred is the coloumn which tells us preferred time slot for showing advertisement to the customers

In [13]:
dataset.mean()

Impressions       42221.645833
Clicks               42.221646
Sales Unit            0.422216
Time preferred        0.187500
dtype: float64

In [14]:
#the average no of Impression are 42221.645833
#the average no of Clicks are 42.221646
#the average no of Sales unit are 0.422216

In [15]:
dataset.isnull().sum()

Impressions       0
Clicks            0
Sales Unit        0
Time preferred    0
dtype: int64

In [16]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [17]:
x

array([[2.45847e+05, 2.45847e+02, 2.45847e+00],
       [1.59674e+05, 1.59674e+02, 1.59674e+00],
       [1.89600e+03, 1.89600e+00, 1.89600e-02],
       [1.78900e+03, 1.78900e+00, 1.78900e-02],
       [1.99000e+03, 1.99000e+00, 1.99000e-02],
       [1.29900e+03, 1.29900e+00, 1.29900e-02],
       [1.80000e+02, 1.80000e-01, 1.80000e-03],
       [1.89000e+02, 1.89000e-01, 1.89000e-03],
       [1.75000e+02, 1.75000e-01, 1.75000e-03],
       [1.83000e+02, 1.83000e-01, 1.83000e-03],
       [5.96000e+02, 5.96000e-01, 5.96000e-03],
       [5.74000e+02, 5.74000e-01, 5.74000e-03],
       [1.75200e+03, 1.75200e+00, 1.75200e-02],
       [1.78900e+03, 1.78900e+00, 1.78900e-02],
       [1.23500e+03, 1.23500e+00, 1.23500e-02],
       [1.54780e+04, 1.54780e+01, 1.54780e-01],
       [1.59630e+04, 1.59630e+01, 1.59630e-01],
       [1.22580e+04, 1.22580e+01, 1.22580e-01],
       [1.89640e+04, 1.89640e+01, 1.89640e-01],
       [1.78460e+04, 1.78460e+01, 1.78460e-01],
       [1.02530e+04, 1.02530e+01, 1.0253

In [18]:
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1], dtype=int64)

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10, random_state =0)

In [20]:
print(x_train)

[[3.21460e+04 3.21460e+01 3.21460e-01]
 [1.33310e+04 1.33310e+01 1.33310e-01]
 [1.06940e+04 1.06940e+01 1.06940e-01]
 [1.89000e+02 1.89000e-01 1.89000e-03]
 [5.96000e+02 5.96000e-01 5.96000e-03]
 [5.74000e+02 5.74000e-01 5.74000e-03]
 [1.27840e+04 1.27840e+01 1.27840e-01]
 [1.23630e+04 1.23630e+01 1.23630e-01]
 [1.02396e+05 1.02396e+02 1.02396e+00]
 [2.54964e+05 2.54964e+02 2.54964e+00]
 [1.89600e+03 1.89600e+00 1.89600e-02]
 [2.10006e+05 2.10006e+02 2.10006e+00]
 [1.89640e+04 1.89640e+01 1.89640e-01]
 [1.54780e+04 1.54780e+01 1.54780e-01]
 [1.58476e+05 1.58476e+02 1.58476e+00]
 [4.85800e+03 4.85800e+00 4.85800e-02]
 [1.59630e+04 1.59630e+01 1.59630e-01]
 [1.47860e+04 1.47860e+01 1.47860e-01]
 [1.02530e+04 1.02530e+01 1.02530e-01]
 [1.59660e+04 1.59660e+01 1.59660e-01]
 [1.75000e+02 1.75000e-01 1.75000e-03]
 [1.78900e+03 1.78900e+00 1.78900e-02]
 [1.84520e+04 1.84520e+01 1.84520e-01]
 [1.29900e+03 1.29900e+00 1.29900e-02]
 [1.22580e+04 1.22580e+01 1.22580e-01]
 [1.96340e+04 1.96340e+01

In [21]:
print(y_train)

[0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 1 0 1 1]


In [22]:
print(x_test)

[[1.42000e+04 1.42000e+01 1.42000e-01]
 [1.99000e+03 1.99000e+00 1.99000e-02]
 [1.20456e+05 1.20456e+02 1.20456e+00]
 [1.52070e+04 1.52070e+01 1.52070e-01]
 [1.63470e+04 1.63470e+01 1.63470e-01]]


In [23]:
print(y_test)

[0 0 1 0 0]


In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [25]:
print(x_train)

[[-0.15421626 -0.15421626 -0.15421626]
 [-0.41624505 -0.41624505 -0.41624505]
 [-0.45296947 -0.45296947 -0.45296947]
 [-0.59926829 -0.59926829 -0.59926829]
 [-0.59360017 -0.59360017 -0.59360017]
 [-0.59390656 -0.59390656 -0.59390656]
 [-0.42386289 -0.42386289 -0.42386289]
 [-0.42972599 -0.42972599 -0.42972599]
 [ 0.82412669  0.82412669  0.82412669]
 [ 2.94887868  2.94887868  2.94887868]
 [-0.5754956  -0.5754956  -0.5754956 ]
 [ 2.32276705  2.32276705  2.32276705]
 [-0.33779657 -0.33779657 -0.33779657]
 [-0.38634466 -0.38634466 -0.38634466]
 [ 1.60512986  1.60512986  1.60512986]
 [-0.53424505 -0.53424505 -0.53424505]
 [-0.37959026 -0.37959026 -0.37959026]
 [-0.39598186 -0.39598186 -0.39598186]
 [-0.45911109 -0.45911109 -0.45911109]
 [-0.37954848 -0.37954848 -0.37954848]
 [-0.59946327 -0.59946327 -0.59946327]
 [-0.57698575 -0.57698575 -0.57698575]
 [-0.34492698 -0.34492698 -0.34492698]
 [-0.58380978 -0.58380978 -0.58380978]
 [-0.43118828 -0.43118828 -0.43118828]
 [-0.32846575 -0.32846575

In [26]:
print(x_test)

[[-0.40414284 -0.40414284 -0.40414284]
 [-0.57418651 -0.57418651 -0.57418651]
 [ 1.07564091  1.07564091  1.07564091]
 [-0.39011877 -0.39011877 -0.39011877]
 [-0.37424245 -0.37424245 -0.37424245]]


In [27]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(random_state=0)

In [28]:
print(classifier.predict(sc.transform([[183,0.183,0.00183]])))


[0]


In [29]:
#Conclusion 
#There are 9 no of preferred time slot of 30 min in a entire day where it is preferable to show the Advertisement

In [30]:
#In night 12am to 2pm and in morning 10:30am to 11:30am these are the timing where the company has received the sales

In [31]:
#Using above algorithm we have classify that we have successfully train the data and classified into 2 categerious
#this timing is preferred and not preferred


In [32]:
#In this way we have used decision tree algorithm to classify time slots which are preferable for conversion campaign
#This will help makketing to take decision about remarketing campaign
