In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
file=pd.read_excel("C:/Users/Administrator/Desktop/Google ads hourly analysis 21th june.xlsx")

In [43]:
file

Sr no  Impressions   Clicks  Cost     CTR        CPC  Cold Leads   \
0   00:00:00          7840     706    689  0.090   0.975921           42   
1   00:30:00          5694     171    508  0.030   2.970760           10   
2   01:00:00          3610      72    495  0.020   6.875000            4   
3   01:30:00           485       5     64  0.010  12.800000            0   
4   02:00:00           125       0     59  0.000   0.000000            0   
5   02:30:00            48       0     12  0.000   0.000000            0   
6   03:00:00            12       0      7  0.000   0.000000            0   
7   03:30:00             6       0      6  0.000   0.000000            0   
8   04:00:00             9       0      9  0.000   0.000000            0   
9   04:30:00             3       0     12  0.010   0.000000            0   
10  05:00:00             6       0     16  0.000   0.000000            0   
11  05:30:00             8       0      4  0.000   0.000000            0   
12  06:00:00             9       0      6  0.010   0.000000            0   
13  06:30:00            12       0     23  0.010   0.000000            0   
14  07:00:00            46       1     27  0.022  27.000000            0   
15  07:30:00           152       3     50  0.020  16.666667            0   
16  08:00:00           164       5     80  0.030  16.000000            0   
17  08:30:00           174       7    150  0.040  21.428571            0   
18  09:00:00          2360      24    265  0.010  11.041667            1   
19  09:30:00          2159     108    314  0.050   2.907407            6   
20  10:00:00          1264      88    326  0.070   3.704545            5   
21  10:30:00          1963     177    465  0.090   2.627119           11   
22  11:00:00          1786     143    329  0.080   2.300699            9   
23  11:30:00          2109     169    384  0.080   1.396450           10   
24  12:00:00          2964     593    396  0.200   0.451939           36   
25  12:30:00          3015     211    465  0.070   2.203791           13   
26  13:00:00          3415     376    465  0.110   0.699468           23   
27  13:30:00          3625     435    402  0.120   0.547126           26   
28  14:00:00          3648     328    426  0.090   0.838415           20   
29  14:30:00          4059     325    486  0.080   0.784615           20   
30  15:00:00          4216     506    501  0.120   0.990119           30   
31  15:30:00          4762     429    263  0.090   0.613054           26   
32  16:00:00          4011     642    469  0.160   0.730530           39   
33  16:30:00          3152     441    498  0.140   1.129252           26   
34  17:00:00          4526     815    569  0.180   0.488344           49   
35  17:30:00          6495     844    548  0.130   0.446682           51   
36  18:00:00          6478    1231    651  0.190   0.461413           74   
37  18:30:00          7985    1198    623  0.150   0.481636           72   
38  19:00:00          7495    1199    528  0.160   0.440367           72   
39  19:30:00          9485    1992    654  0.210   0.328313          120   
40  20:00:00          9465    2177    715  0.230   0.221406          131   
41  20:30:00          7521    1805    795  0.240   0.261496          108   
42  21:00:00          5969    1134    742  0.190   0.476190           68   
43  21:30:00          5899    1062    798  0.180   0.459510           64   
44  22:00:00          6891    1654    783  0.240   0.307739           99   
45  22:30:00          6203     992    846  0.160   0.852823           60   
46  23:00:00          6123     857    658  0.140   0.767795           51   
47  23:30:00          8811     705    798  0.080   1.131915           42   

    Warm Leads  Hot Leads  
0            4          2  
1            1          1  
2            0          0  
3            0          0  
4            0          0  
5            0          0  
6            0          0  
7            0          0  
8            0          0  
9 

In [44]:
file.head()

Sr no  Impressions   Clicks  Cost    CTR        CPC  Cold Leads   \
0  00:00:00          7840     706    689  0.09   0.975921           42   
1  00:30:00          5694     171    508  0.03   2.970760           10   
2  01:00:00          3610      72    495  0.02   6.875000            4   
3  01:30:00           485       5     64  0.01  12.800000            0   
4  02:00:00           125       0     59  0.00   0.000000            0   

   Warm Leads  Hot Leads  
0           4          2  
1           1          1  
2           0          0  
3           0          0  
4           0          0

In [45]:
dataset=file.drop("Sr no",axis=1)

In [46]:
dataset

Impressions   Clicks  Cost     CTR        CPC  Cold Leads   Warm Leads  \
0           7840     706    689  0.090   0.975921           42           4   
1           5694     171    508  0.030   2.970760           10           1   
2           3610      72    495  0.020   6.875000            4           0   
3            485       5     64  0.010  12.800000            0           0   
4            125       0     59  0.000   0.000000            0           0   
5             48       0     12  0.000   0.000000            0           0   
6             12       0      7  0.000   0.000000            0           0   
7              6       0      6  0.000   0.000000            0           0   
8              9       0      9  0.000   0.000000            0           0   
9              3       0     12  0.010   0.000000            0           0   
10             6       0     16  0.000   0.000000            0           0   
11             8       0      4  0.000   0.000000            0           0   
12             9       0      6  0.010   0.000000            0           0   
13            12       0     23  0.010   0.000000            0           0   
14            46       1     27  0.022  27.000000            0           0   
15           152       3     50  0.020  16.666667            0           0   
16           164       5     80  0.030  16.000000            0           0   
17           174       7    150  0.040  21.428571            0           0   
18          2360      24    265  0.010  11.041667            1           0   
19          2159     108    314  0.050   2.907407            6           1   
20          1264      88    326  0.070   3.704545            5           1   
21          1963     177    465  0.090   2.627119           11           1   
22          1786     143    329  0.080   2.300699            9           1   
23          2109     169    384  0.080   1.396450           10           1   
24          2964     593    396  0.200   0.451939           36           4   
25          3015     211    465  0.070   2.203791           13           1   
26          3415     376    465  0.110   0.699468           23           2   
27          3625     435    402  0.120   0.547126           26           3   
28          3648     328    426  0.090   0.838415           20           2   
29          4059     325    486  0.080   0.784615           20           2   
30          4216     506    501  0.120   0.990119           30          13   
31          4762     429    263  0.090   0.613054           26          15   
32          4011     642    469  0.160   0.730530           39           9   
33          3152     441    498  0.140   1.129252           26          12   
34          4526     815    569  0.180   0.488344           49          16   
35          6495     844    548  0.130   0.446682           51          15   
36          6478    1231    651  0.190   0.461413           74          14   
37          7985    1198    623  0.150   0.481636           72          13   
38          7495    1199    528  0.160   0.440367           72          11   
39          9485    1992    654  0.210   0.328313          120          12   
40          9465    2177    715  0.230   0.221406          131          13   
41          7521    1805    795  0.240   0.261496          108          11   
42          5969    1134    742  0.190   0.476190           68          12   
43          5899    1062    798  0.180   0.459510           64          16   
44          6891    1654    783  0.240   0.307739           99          10   
45          6203     992    846  0.160   0.852823           60          17   
46          6123     857    658  0.140   0.767795           51          15   
47          8811     705    798  0.080   1.131915           42          14   

    Hot Leads  
0           2  
1           1  
2           0  
3           0  
4           0  
5           0  
6           0  
7           0  
8           0  
9           0  
10   

In [47]:
a=dataset.isnull().sum()

In [48]:
a

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [49]:
dataset


Impressions   Clicks  Cost     CTR        CPC  Cold Leads   Warm Leads  \
0           7840     706    689  0.090   0.975921           42           4   
1           5694     171    508  0.030   2.970760           10           1   
2           3610      72    495  0.020   6.875000            4           0   
3            485       5     64  0.010  12.800000            0           0   
4            125       0     59  0.000   0.000000            0           0   
5             48       0     12  0.000   0.000000            0           0   
6             12       0      7  0.000   0.000000            0           0   
7              6       0      6  0.000   0.000000            0           0   
8              9       0      9  0.000   0.000000            0           0   
9              3       0     12  0.010   0.000000            0           0   
10             6       0     16  0.000   0.000000            0           0   
11             8       0      4  0.000   0.000000            0           0   
12             9       0      6  0.010   0.000000            0           0   
13            12       0     23  0.010   0.000000            0           0   
14            46       1     27  0.022  27.000000            0           0   
15           152       3     50  0.020  16.666667            0           0   
16           164       5     80  0.030  16.000000            0           0   
17           174       7    150  0.040  21.428571            0           0   
18          2360      24    265  0.010  11.041667            1           0   
19          2159     108    314  0.050   2.907407            6           1   
20          1264      88    326  0.070   3.704545            5           1   
21          1963     177    465  0.090   2.627119           11           1   
22          1786     143    329  0.080   2.300699            9           1   
23          2109     169    384  0.080   1.396450           10           1   
24          2964     593    396  0.200   0.451939           36           4   
25          3015     211    465  0.070   2.203791           13           1   
26          3415     376    465  0.110   0.699468           23           2   
27          3625     435    402  0.120   0.547126           26           3   
28          3648     328    426  0.090   0.838415           20           2   
29          4059     325    486  0.080   0.784615           20           2   
30          4216     506    501  0.120   0.990119           30          13   
31          4762     429    263  0.090   0.613054           26          15   
32          4011     642    469  0.160   0.730530           39           9   
33          3152     441    498  0.140   1.129252           26          12   
34          4526     815    569  0.180   0.488344           49          16   
35          6495     844    548  0.130   0.446682           51          15   
36          6478    1231    651  0.190   0.461413           74          14   
37          7985    1198    623  0.150   0.481636           72          13   
38          7495    1199    528  0.160   0.440367           72          11   
39          9485    1992    654  0.210   0.328313          120          12   
40          9465    2177    715  0.230   0.221406          131          13   
41          7521    1805    795  0.240   0.261496          108          11   
42          5969    1134    742  0.190   0.476190           68          12   
43          5899    1062    798  0.180   0.459510           64          16   
44          6891    1654    783  0.240   0.307739           99          10   
45          6203     992    846  0.160   0.852823           60          17   
46          6123     857    658  0.140   0.767795           51          15   
47          8811     705    798  0.080   1.131915           42          14   

    Hot Leads  
0           2  
1           1  
2           0  
3           0  
4           0  
5           0  
6           0  
7           0  
8           0  
9           0  
10   

In [50]:
dataset1=dataset.drop(["CPC","CTR","Warm Leads"],axis=1)

In [51]:
dataset1

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0           7840     706    689           42          2
1           5694     171    508           10          1
2           3610      72    495            4          0
3            485       5     64            0          0
4            125       0     59            0          0
5             48       0     12            0          0
6             12       0      7            0          0
7              6       0      6            0          0
8              9       0      9            0          0
9              3       0     12            0          0
10             6       0     16            0          0
11             8       0      4            0          0
12             9       0      6            0          0
13            12       0     23            0          0
14            46       1     27            0          0
15           152       3     50            0          0
16           164       5     80            0          0
17           174       7    150            0          0
18          2360      24    265            1          0
19          2159     108    314            6          1
20          1264      88    326            5          1
21          1963     177    465           11          1
22          1786     143    329            9          1
23          2109     169    384           10          1
24          2964     593    396           36          2
25          3015     211    465           13          1
26          3415     376    465           23          1
27          3625     435    402           26          2
28          3648     328    426           20          1
29          4059     325    486           20          1
30          4216     506    501           30          4
31          4762     429    263           26          6
32          4011     642    469           39          2
33          3152     441    498           26          9
34          4526     815    569           49          3
35          6495     844    548           51          7
36          6478    1231    651           74          6
37          7985    1198    623           72          5
38          7495    1199    528           72          7
39          9485    1992    654          120          1
40          9465    2177    715          131          7
41          7521    1805    795          108          3
42          5969    1134    742           68          9
43          5899    1062    798           64          9
44          6891    1654    783           99          6
45          6203     992    846           60          8
46          6123     857    658           51          8
47          8811     705    798           42          6

In [52]:
dataset1.head()

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0          7840     706    689           42          2
1          5694     171    508           10          1
2          3610      72    495            4          0
3           485       5     64            0          0
4           125       0     59            0          0

In [53]:
# descriptive analysis 

In [54]:
dataset.sum()

Impressions     166257.000000
Clicks           23630.000000
Cost             18379.000000
CTR                  4.332000
CPC                144.808744
Cold Leads        1418.000000
Warm Leads         262.000000
Hot Leads          122.000000
dtype: float64

In [55]:
#Impressions are no of visible ads to customers
#Total impressions are 166257.000000
#Clicks indicates total no of customers who clicked on our ads
#total no of clicks ad 23630.000000


In [56]:
#Cost indicates cost per click and impression for ads
#Total cost are 18379.000000 

In [58]:
#CPC indicates dividing the ads cost by the number of clicks generated by an ads
#total CPC is 144.808744

In [59]:
#Cold lead indicates those  customers shows only intrest in Ads
#Warm lead indicates those customers are showing intrest in Ads and providing their contact details
#Hot lead indicates those customers are highly intrested and are ready to buy 

In [60]:
#Total no of Cold lead are 1418.000000
#Total no of Warm lead are 262.000000
#Total no of Hot lead are 122.000000 

In [61]:
dataset.mean()

Impressions     3463.687500
Clicks           492.291667
Cost             382.895833
CTR                0.090250
CPC                3.016849
Cold Leads        29.541667
Warm Leads         5.458333
Hot Leads          2.541667
dtype: float64

In [62]:
#the average no of Impression are 3463.687500 
#the average no of Clicks are 492.291667
#the average no of cost is 382.895833
#the average no of CTR is 0.090250 
#the average no of CPC is 3.016849
#the average no of cold lead  29.541667 
#the average no of warm lead 5.458333 
#the average no of hot lead 2.541667

In [63]:
#Individual ratio
#Individual ratio of cold lead and warm lead is 9.52%
#Individual ratio of warm lead and hot lead is 50%
#Individual ratio of cold lead and hot lead is 4.76%


In [64]:
#On an average ratio
#on an average ratio of cold lead and warm lead is 18.47%
#on an average ratio of warm lead and hot lead is 46.56%
#on an average ratio of cold lead and hot lead is 8.60%

In [65]:
x=dataset1.iloc[:,:-1].values
y=dataset1.iloc[:,-1].values

In [66]:
x

array([[7840,  706,  689,   42],
       [5694,  171,  508,   10],
       [3610,   72,  495,    4],
       [ 485,    5,   64,    0],
       [ 125,    0,   59,    0],
       [  48,    0,   12,    0],
       [  12,    0,    7,    0],
       [   6,    0,    6,    0],
       [   9,    0,    9,    0],
       [   3,    0,   12,    0],
       [   6,    0,   16,    0],
       [   8,    0,    4,    0],
       [   9,    0,    6,    0],
       [  12,    0,   23,    0],
       [  46,    1,   27,    0],
       [ 152,    3,   50,    0],
       [ 164,    5,   80,    0],
       [ 174,    7,  150,    0],
       [2360,   24,  265,    1],
       [2159,  108,  314,    6],
       [1264,   88,  326,    5],
       [1963,  177,  465,   11],
       [1786,  143,  329,    9],
       [2109,  169,  384,   10],
       [2964,  593,  396,   36],
       [3015,  211,  465,   13],
       [3415,  376,  465,   23],
       [3625,  435,  402,   26],
       [3648,  328,  426,   20],
       [4059,  325,  486,   20],
       [42

In [67]:
y

array([2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 2, 1, 1, 2, 1, 1, 4, 6, 2, 9, 3, 7, 6, 5, 7, 1, 7, 3, 9, 9,
       6, 8, 8, 6], dtype=int64)

In [121]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10, random_state =0)

In [122]:
print(x_train)

[[7985 1198  623   72]
 [4526  815  569   49]
 [9465 2177  715  131]
 [   6    0    6    0]
 [   6    0   16    0]
 [   8    0    4    0]
 [4762  429  263   26]
 [3152  441  498   26]
 [3625  435  402   26]
 [8811  705  798   42]
 [3610   72  495    4]
 [6123  857  658   51]
 [2360   24  265    1]
 [ 152    3   50    0]
 [3648  328  426   20]
 [1786  143  329    9]
 [ 164    5   80    0]
 [7521 1805  795  108]
 [1264   88  326    5]
 [5969 1134  742   68]
 [   9    0    9    0]
 [  12    0   23    0]
 [3015  211  465   13]
 [  48    0   12    0]
 [ 174    7  150    0]
 [6495  844  548   51]
 [  46    1   27    0]
 [7495 1199  528   72]
 [5694  171  508   10]
 [   9    0    6    0]
 [5899 1062  798   64]
 [2964  593  396   36]
 [  12    0    7    0]
 [2109  169  384   10]
 [6478 1231  651   74]
 [1963  177  465   11]
 [2159  108  314    6]
 [   3    0   12    0]
 [9485 1992  654  120]
 [6203  992  846   60]
 [ 485    5   64    0]
 [7840  706  689   42]
 [6891 1654  783   99]]


In [123]:
print(y_train)

[5 3 7 0 0 0 6 9 2 6 0 8 0 0 1 1 0 3 1 9 0 0 1 0 0 7 0 7 1 0 9 2 0 1 6 1 1
 0 1 8 0 2 6]


In [124]:
print(x_test)

[[4059  325  486   20]
 [ 125    0   59    0]
 [3415  376  465   23]
 [4216  506  501   30]
 [4011  642  469   39]]


In [125]:
print(y_test)

[1 0 1 4 2]


In [126]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [127]:
print(x_train)

[[ 1.44694243  1.14189931  0.85763045  1.14307455]
 [ 0.33140535  0.50940546  0.66596367  0.5115099 ]
 [ 1.92424653  2.75863948  1.18417387  2.76317518]
 [-1.12630717 -0.83650183 -1.33234005 -0.83399741]
 [-1.12630717 -0.83650183 -1.2968462  -0.83399741]
 [-1.12566217 -0.83650183 -1.33943882 -0.83399741]
 [ 0.407516   -0.12804266 -0.42014812 -0.12005476]
 [-0.11171346 -0.10822562  0.41395734 -0.12005476]
 [ 0.04083035 -0.11813414  0.07321638 -0.12005476]
 [ 1.71332972  0.32774926  1.47877282  0.31929457]
 [ 0.03599281 -0.71759959  0.40330918 -0.72416008]
 [ 0.84644227  0.5787651   0.98185893  0.56642856]
 [-0.36713565 -0.79686775 -0.41304935 -0.80653808]
 [-1.07922177 -0.83154757 -1.17616712 -0.83399741]
 [ 0.04824791 -0.29483607  0.15840162 -0.28481075]
 [-0.55225224 -0.60034877 -0.18588872 -0.58686341]
 [-1.07535174 -0.82824473 -1.06968557 -0.83399741]
 [ 1.29730114  2.14431124  1.46812466  2.13161053]
 [-0.72059869 -0.69117687 -0.19653687 -0.69670075]
 [ 0.79677684  1.03620843  1.28

In [128]:
print(x_test)

[[ 1.80796553e-01 -2.99790335e-01  3.71364717e-01 -2.84810754e-01]
 [-1.08792934e+00 -8.36501830e-01 -1.14422265e+00 -8.33997409e-01]
 [-2.68952310e-02 -2.15567916e-01  2.96827633e-01 -2.02432756e-01]
 [ 2.31429488e-01 -8.83317666e-04  4.24605491e-01 -1.02174261e-02]
 [ 1.65316420e-01  2.23709800e-01  3.11025173e-01  2.36916569e-01]]


In [129]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(random_state=0)

In [130]:
print(classifier.predict(sc.transform([[9489,1423,628,57]])))

[5]


In [131]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [6 4]
 [9 2]]


In [132]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


0.6

In [133]:
#Accuracy is 60%

In [134]:
#Conclusion 
#There are 31 no of preferred time slot of 30 min in a entire day where it is preferable to show the Advertisement
#In which 3:00 pm to 11:30 pm from Afternoon to night company has generated more no of hot leads so we concluded that
#We can show ads to people in above given time slots as more no of people use their mobile phones in evening and night
#so this time is preferrable.
#The maximum cost we used to show ad is in time slot of 3:00 pm to 11:30 pm where we generate 106 no of hot leads
#In each no of time slot
# In the time slots company has get more no of impressions, clicks,cold lead,warm lead,hot lead.

In [48]:
#There are 17 no of non preferred time slots and that company dosent get hot lead

In [49]:
#In time slots where company dosent get hot lead company spent 1285 rs 
#In reamaning time slots where company got hot leads company spent 17094 rs
#So total cost spent by  company on every time slot is 18379 rs
#93.00% of cost spent by company make profit by getting HOT Leads.

In [51]:
#We suggest we can reduce the cost by 6.99% not spending in the 1:00 am to 9:00 am time slots

In [ ]:
#On an average company spent 140.11rs for each hot lead.