In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
file=pd.read_excel("C:/Users/Administrator/Desktop/Google ads hourly analysis 19th june.xlsx")

In [3]:
file

Sr no  Impressions   Clicks  Cost      CTR        CPC  Cold Leads   \
0   00:00:00          5941     356    594  0.0600   1.666667           11   
1   00:30:00          4511     180    451  0.0400   2.500000            9   
2   01:00:00          3378     101    338  0.0300   3.333333            6   
3   01:30:00           652      26     65  0.0400   2.500000            1   
4   02:00:00           421       8     42  0.0200   5.000000            0   
5   02:30:00           110       2     11  0.0200   5.000000            0   
6   03:00:00            56       1      6  0.0200   5.000000            0   
7   03:30:00            42       1      4  0.0120   8.333333            0   
8   04:00:00             3       0      0  0.0110   9.090909            0   
9   04:30:00             8       0      1  0.0190   5.263158            0   
10  05:00:00            95       1     10  0.0140   7.142857            0   
11  05:30:00            64       1      6  0.0200   5.000000            0   
12  06:00:00            26       0      3  0.0020  50.000000            0   
13  06:30:00           193       4     19  0.0200   5.000000            0   
14  07:00:00           236       5     24  0.0220   4.545455            0   
15  07:30:00           463      23     46  0.0500   2.000000            1   
16  08:00:00           896      54     90  0.0600   1.666667            2   
17  08:30:00           486      34     49  0.0700   1.428571            1   
18  09:00:00           785      71     79  0.0900   1.111111            1   
19  09:30:00          1245     149    125  0.1200   0.833333            2   
20  10:00:00          1755     228    176  0.1300   0.769231            3   
21  10:30:00          1865     106    187  0.0569   1.757469            4   
22  11:00:00          2658     399    266  0.1500   0.666667            5   
23  11:30:00          3255     391    326  0.1200   0.833333            7   
24  12:00:00          3284     427    328  0.1300   0.769231            6   
25  12:30:00          4651     558    465  0.1200   0.833333            9   
26  13:00:00          4895     685    490  0.1400   0.714286           10   
27  13:30:00          4752     665    475  0.1400   0.714286            9   
28  14:00:00          4665     606    467  0.1300   0.769231            9   
29  14:30:00          4958     694    496  0.1400   0.714286           10   
30  15:00:00          5320     745    532  0.1400   0.714286           10   
31  15:30:00          5968     836    597  0.1400   0.714286           12   
32  16:00:00          5673     794    567  0.1400   0.714286           11   
33  16:30:00          4865    1216    487  0.2500   0.400000            9   
34  17:00:00          6593    1055    659  0.1600   0.625000           13   
35  17:30:00          8945    1700    895  0.1900   0.526316           18   
36  18:00:00          8444    1773    844  0.2100   0.476190           17   
37  18:30:00          8452    1944    845  0.2300   0.434783           17   
38  19:00:00          8757    2277    876  0.2600   0.384615           17   
39  19:30:00          8968    1883    897  0.2100   0.476190           18   
40  20:00:00          9425    1414    943  0.1500   0.666667           19   
41  20:30:00          9120    1277    912  0.1400   0.714286           18   
42  21:00:00          8945    1431    895  0.1600   0.625000           18   
43  21:30:00          7863    1179    786  0.1500   0.666667           16   
44  22:00:00          7521    1203    752  0.1600   0.625000           15   
45  22:30:00          9632    1830    963  0.1900   0.526316           19   
46  23:00:00         10230    1739   1023  0.1700   0.588235           20   
47  23:30:00          9452    1512    945  0.1600   0.625000           19   

    Warm Leads  Hot Leads  
0          5.0          2  
1          4.0          2  
2          3.0          1  
3          NaN          0  
4          0.0          0  
5          0.0          0  
6          0.0          0  
7        

In [4]:
file.head()

Sr no  Impressions   Clicks  Cost    CTR       CPC  Cold Leads   \
0  00:00:00          5941     356    594  0.06  1.666667           11   
1  00:30:00          4511     180    451  0.04  2.500000            9   
2  01:00:00          3378     101    338  0.03  3.333333            6   
3  01:30:00           652      26     65  0.04  2.500000            1   
4  02:00:00           421       8     42  0.02  5.000000            0   

   Warm Leads  Hot Leads  
0         5.0          2  
1         4.0          2  
2         3.0          1  
3         NaN          0  
4         0.0          0

In [5]:
dataset=file.drop("Sr no",axis=1)

In [6]:
dataset

Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           5941     356    594  0.0600   1.666667           11         5.0   
1           4511     180    451  0.0400   2.500000            9         4.0   
2           3378     101    338  0.0300   3.333333            6         3.0   
3            652      26     65  0.0400   2.500000            1         NaN   
4            421       8     42  0.0200   5.000000            0         0.0   
5            110       2     11  0.0200   5.000000            0         0.0   
6             56       1      6  0.0200   5.000000            0         0.0   
7             42       1      4  0.0120   8.333333            0         0.0   
8              3       0      0  0.0110   9.090909            0         0.0   
9              8       0      1  0.0190   5.263158            0         0.0   
10            95       1     10  0.0140   7.142857            0         0.0   
11            64       1      6  0.0200   5.000000            0         0.0   
12            26       0      3  0.0020  50.000000            0         0.0   
13           193       4     19  0.0200   5.000000            0         0.0   
14           236       5     24  0.0220   4.545455            0         0.0   
15           463      23     46  0.0500   2.000000            1         0.0   
16           896      54     90  0.0600   1.666667            2         1.0   
17           486      34     49  0.0700   1.428571            1         0.0   
18           785      71     79  0.0900   1.111111            1         0.0   
19          1245     149    125  0.1200   0.833333            2         1.0   
20          1755     228    176  0.1300   0.769231            3         1.0   
21          1865     106    187  0.0569   1.757469            4         2.0   
22          2658     399    266  0.1500   0.666667            5         2.0   
23          3255     391    326  0.1200   0.833333            7         3.0   
24          3284     427    328  0.1300   0.769231            6         3.0   
25          4651     558    465  0.1200   0.833333            9         4.0   
26          4895     685    490  0.1400   0.714286           10         5.0   
27          4752     665    475  0.1400   0.714286            9         4.0   
28          4665     606    467  0.1300   0.769231            9         4.0   
29          4958     694    496  0.1400   0.714286           10         5.0   
30          5320     745    532  0.1400   0.714286           10         5.0   
31          5968     836    597  0.1400   0.714286           12         6.0   
32          5673     794    567  0.1400   0.714286           11         4.0   
33          4865    1216    487  0.2500   0.400000            9         4.0   
34          6593    1055    659  0.1600   0.625000           13         6.0   
35          8945    1700    895  0.1900   0.526316           18         9.0   
36          8444    1773    844  0.2100   0.476190           17         8.0   
37          8452    1944    845  0.2300   0.434783           17         8.0   
38          8757    2277    876  0.2600   0.384615           17         8.0   
39          8968    1883    897  0.2100   0.476190           18         9.0   
40          9425    1414    943  0.1500   0.666667           19         9.0   
41          9120    1277    912  0.1400   0.714286           18         9.0   
42          8945    1431    895  0.1600   0.625000           18         9.0   
43          7863    1179    786  0.1500   0.666667           16         8.0   
44          7521    1203    752  0.1600   0.625000           15         7.0   
45          9632    1830    963  0.1900   0.526316           19         9.0   
46         10230    1739   1023  0.1700   0.588235           20        10.0   
47          9452    1512    945  0.1600   0.625000           19         9.0   

    Hot Leads  
0           2  
1           2  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [7]:
dataset.isnull().sum()

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      1
Hot Leads       0
dtype: int64

In [8]:
dataset1=dataset.fillna({"Warm Leads":0.0})

In [9]:
dataset1.isnull().sum()

Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [10]:
dataset1


Impressions   Clicks  Cost      CTR        CPC  Cold Leads   Warm Leads  \
0           5941     356    594  0.0600   1.666667           11         5.0   
1           4511     180    451  0.0400   2.500000            9         4.0   
2           3378     101    338  0.0300   3.333333            6         3.0   
3            652      26     65  0.0400   2.500000            1         0.0   
4            421       8     42  0.0200   5.000000            0         0.0   
5            110       2     11  0.0200   5.000000            0         0.0   
6             56       1      6  0.0200   5.000000            0         0.0   
7             42       1      4  0.0120   8.333333            0         0.0   
8              3       0      0  0.0110   9.090909            0         0.0   
9              8       0      1  0.0190   5.263158            0         0.0   
10            95       1     10  0.0140   7.142857            0         0.0   
11            64       1      6  0.0200   5.000000            0         0.0   
12            26       0      3  0.0020  50.000000            0         0.0   
13           193       4     19  0.0200   5.000000            0         0.0   
14           236       5     24  0.0220   4.545455            0         0.0   
15           463      23     46  0.0500   2.000000            1         0.0   
16           896      54     90  0.0600   1.666667            2         1.0   
17           486      34     49  0.0700   1.428571            1         0.0   
18           785      71     79  0.0900   1.111111            1         0.0   
19          1245     149    125  0.1200   0.833333            2         1.0   
20          1755     228    176  0.1300   0.769231            3         1.0   
21          1865     106    187  0.0569   1.757469            4         2.0   
22          2658     399    266  0.1500   0.666667            5         2.0   
23          3255     391    326  0.1200   0.833333            7         3.0   
24          3284     427    328  0.1300   0.769231            6         3.0   
25          4651     558    465  0.1200   0.833333            9         4.0   
26          4895     685    490  0.1400   0.714286           10         5.0   
27          4752     665    475  0.1400   0.714286            9         4.0   
28          4665     606    467  0.1300   0.769231            9         4.0   
29          4958     694    496  0.1400   0.714286           10         5.0   
30          5320     745    532  0.1400   0.714286           10         5.0   
31          5968     836    597  0.1400   0.714286           12         6.0   
32          5673     794    567  0.1400   0.714286           11         4.0   
33          4865    1216    487  0.2500   0.400000            9         4.0   
34          6593    1055    659  0.1600   0.625000           13         6.0   
35          8945    1700    895  0.1900   0.526316           18         9.0   
36          8444    1773    844  0.2100   0.476190           17         8.0   
37          8452    1944    845  0.2300   0.434783           17         8.0   
38          8757    2277    876  0.2600   0.384615           17         8.0   
39          8968    1883    897  0.2100   0.476190           18         9.0   
40          9425    1414    943  0.1500   0.666667           19         9.0   
41          9120    1277    912  0.1400   0.714286           18         9.0   
42          8945    1431    895  0.1600   0.625000           18         9.0   
43          7863    1179    786  0.1500   0.666667           16         8.0   
44          7521    1203    752  0.1600   0.625000           15         7.0   
45          9632    1830    963  0.1900   0.526316           19         9.0   
46         10230    1739   1023  0.1700   0.588235           20        10.0   
47          9452    1512    945  0.1600   0.625000           19         9.0   

    Hot Leads  
0           2  
1           2  
2           1  
3           0  
4           0  
5           0  
6           0  
7   

In [11]:
dataset2=dataset1.drop(["CPC","CTR","Warm Leads"],axis=1)

In [12]:
dataset2

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0           5941     356    594           11          2
1           4511     180    451            9          2
2           3378     101    338            6          1
3            652      26     65            1          0
4            421       8     42            0          0
5            110       2     11            0          0
6             56       1      6            0          0
7             42       1      4            0          0
8              3       0      0            0          0
9              8       0      1            0          0
10            95       1     10            0          0
11            64       1      6            0          0
12            26       0      3            0          0
13           193       4     19            0          0
14           236       5     24            0          0
15           463      23     46            1          0
16           896      54     90            2          0
17           486      34     49            1          0
18           785      71     79            1          0
19          1245     149    125            2          0
20          1755     228    176            3          0
21          1865     106    187            4          1
22          2658     399    266            5          1
23          3255     391    326            7          1
24          3284     427    328            6          1
25          4651     558    465            9          1
26          4895     685    490           10          2
27          4752     665    475            9          2
28          4665     606    467            9          2
29          4958     694    496           10          2
30          5320     745    532           10          2
31          5968     836    597           12          2
32          5673     794    567           11          2
33          4865    1216    487            9          1
34          6593    1055    659           13          2
35          8945    1700    895           18          3
36          8444    1773    844           17          3
37          8452    1944    845           17          4
38          8757    2277    876           17          3
39          8968    1883    897           18          3
40          9425    1414    943           19          4
41          9120    1277    912           18          4
42          8945    1431    895           18          4
43          7863    1179    786           16          3
44          7521    1203    752           15          3
45          9632    1830    963           19          4
46         10230    1739   1023           20          4
47          9452    1512    945           19          4

In [13]:
dataset2.head()

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0          5941     356    594           11          2
1          4511     180    451            9          2
2          3378     101    338            6          1
3           652      26     65            1          0
4           421       8     42            0          0

In [14]:
# descriptive analysis 

In [15]:
dataset1.sum()

Impressions     200522.000000
Clicks           31584.000000
Cost             20057.000000
CTR                  5.206900
CPC                145.459869
Cold Leads         392.000000
Warm Leads         184.000000
Hot Leads           73.000000
dtype: float64

In [16]:
#Impressions are no of visible ads to customers
#Total impressions are 200522.000000
#Clicks indicates total no of customers who clicked on our ads
#total no of clicks ad 31584.000000


In [17]:
#Cost indicates cost per click and impression for ads
#Total cost are  20057.000000

In [18]:
#CTR indicates the no of clicks that your ad recives divided by the no of times your ad is shown 
#Total CTR is 5.206900

In [19]:
#CPC indicates dividing the ads cost by the number of clicks generated by an ads
#total CPC is 145.459869

In [20]:
#Cold lead indicates those  customers shows only intrest in Ads
#Warm lead indicates those customers are showing intrest in Ads and providing their contact details
#Hot lead indicates those customers are highly intrested and are ready to buy 

In [21]:
#Total no of Cold lead are 392.000000
#Total no of Warm lead are 184.000000
#Total no of Hot lead are 73.000000

In [22]:
dataset1.mean()

Impressions     4177.541667
Clicks           658.000000
Cost             417.854167
CTR                0.108477
CPC                3.030414
Cold Leads         8.166667
Warm Leads         3.833333
Hot Leads          1.520833
dtype: float64

In [23]:
#the average no of Impression are 4177.541667
#the average no of Clicks are 658.000000
#the average no pf cost is 417.854167
#the average no of CTR is 0.108477
#the average no of CPC is 3.030414
#the average no of cold lead  8.166667
#the average no of warm lead  3.833333
#the average no of hot lead  1.520833

In [24]:
#Individual ratio
#Individual ratio of cold lead and warm lead is 45.45% 
#Individual ratio of warm lead and hot lead is 40%
#Individual ratio of cold lead and hot lead is 18.18%


In [25]:
#On an average ratio
#on an average ratio of cold lead and warm lead is 46.93% 
#on an average ratio of warm lead and hot lead is 39.67%
#on an average ratio of cold lead and hot lead is 18.62%

In [26]:
x=dataset2.iloc[:,:-1].values
y=dataset2.iloc[:,-1].values

In [27]:
x

array([[ 5941,   356,   594,    11],
       [ 4511,   180,   451,     9],
       [ 3378,   101,   338,     6],
       [  652,    26,    65,     1],
       [  421,     8,    42,     0],
       [  110,     2,    11,     0],
       [   56,     1,     6,     0],
       [   42,     1,     4,     0],
       [    3,     0,     0,     0],
       [    8,     0,     1,     0],
       [   95,     1,    10,     0],
       [   64,     1,     6,     0],
       [   26,     0,     3,     0],
       [  193,     4,    19,     0],
       [  236,     5,    24,     0],
       [  463,    23,    46,     1],
       [  896,    54,    90,     2],
       [  486,    34,    49,     1],
       [  785,    71,    79,     1],
       [ 1245,   149,   125,     2],
       [ 1755,   228,   176,     3],
       [ 1865,   106,   187,     4],
       [ 2658,   399,   266,     5],
       [ 3255,   391,   326,     7],
       [ 3284,   427,   328,     6],
       [ 4651,   558,   465,     9],
       [ 4895,   685,   490,    10],
 

In [28]:
y

array([2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 3, 4, 3, 3, 4, 4, 4, 3,
       3, 4, 4, 4], dtype=int64)

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10, random_state =0)

In [30]:
print(x_train)

[[ 8452  1944   845    17]
 [ 6593  1055   659    13]
 [ 9425  1414   943    19]
 [   42     1     4     0]
 [   95     1    10     0]
 [   64     1     6     0]
 [ 5968   836   597    12]
 [ 4865  1216   487     9]
 [ 4752   665   475     9]
 [ 9452  1512   945    19]
 [ 3378   101   338     6]
 [10230  1739  1023    20]
 [  785    71    79     1]
 [  463    23    46     1]
 [ 4665   606   467     9]
 [ 2658   399   266     5]
 [  896    54    90     2]
 [ 9120  1277   912    18]
 [ 1755   228   176     3]
 [ 8945  1431   895    18]
 [    3     0     0     0]
 [  193     4    19     0]
 [ 4651   558   465     9]
 [  110     2    11     0]
 [  486    34    49     1]
 [ 8945  1700   895    18]
 [  236     5    24     0]
 [ 8757  2277   876    17]
 [ 4511   180   451     9]
 [   26     0     3     0]
 [ 7863  1179   786    16]
 [ 3284   427   328     6]
 [   56     1     6     0]
 [ 3255   391   326     7]
 [ 8444  1773   844    17]
 [ 1865   106   187     4]
 [ 1245   149   125     2]
 

In [31]:
print(y_train)

[4 2 4 0 0 0 2 1 2 4 1 4 0 0 2 1 0 4 0 4 0 0 1 0 0 3 0 3 2 0 3 1 0 1 3 1 0
 0 3 4 0 2 3]


In [32]:
print(x_test)

[[4958  694  496   10]
 [ 421    8   42    0]
 [4895  685  490   10]
 [5320  745  532   10]
 [5673  794  567   11]]


In [33]:
print(y_test)

[2 0 2 2 2]


In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [35]:
print(x_train)

[[ 1.18213428e+00  1.79469516e+00  1.18142786e+00  1.21259168e+00]
 [ 6.69072303e-01  5.45818109e-01  6.68031498e-01  6.63734395e-01]
 [ 1.45067075e+00  1.05014529e+00  1.45192702e+00  1.48702033e+00]
 [-1.13892609e+00 -9.34852767e-01 -1.13989654e+00 -1.12005179e+00]
 [-1.12429872e+00 -9.34852767e-01 -1.12333537e+00 -1.12005179e+00]
 [-1.13285435e+00 -9.34852767e-01 -1.13437615e+00 -1.12005179e+00]
 [ 4.96579707e-01  2.38164483e-01  4.96899378e-01  5.26520073e-01]
 [ 1.92164774e-01  7.71992692e-01  1.93277875e-01  1.14877107e-01]
 [ 1.60978113e-01 -2.05821158e-03  1.60155529e-01  1.14877107e-01]
 [ 1.45812243e+00  1.18781677e+00  1.45744741e+00  1.48702033e+00]
 [-2.18229609e-01 -7.94371660e-01 -2.17991253e-01 -2.96765859e-01]
 [ 1.67284121e+00  1.50670889e+00  1.67274265e+00  1.62423465e+00]
 [-9.33866890e-01 -8.36515992e-01 -9.32881884e-01 -9.82837470e-01]
 [-1.02273507e+00 -9.03946924e-01 -1.02396833e+00 -9.82837470e-01]
 [ 1.36967144e-01 -8.49420652e-02  1.38073965e-01  1.14877107e

In [36]:
print(x_test)

[[ 0.21783167  0.03868131  0.21811963  0.25209143]
 [-1.03432658 -0.92501909 -1.03500912 -1.12005179]
 [ 0.20044442  0.02603801  0.20155846  0.25209143]
 [ 0.31773938  0.11032667  0.31748667  0.25209143]
 [ 0.4151632   0.17916242  0.41409351  0.38930575]]


In [37]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(random_state=0)

In [48]:
print(classifier.predict(sc.transform([[3365,111,324,5]])))

[1]


In [49]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]]


In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1 0]
 [0 4]]


1.0

In [ ]:
# Accuracy is 100%

In [51]:
#Conclusion 
#There are 30 no of preferred time slot of 30 min in a entire day where it is preferable to show the Advertisement
#In which 5:30 pm to 11:30 pm from evening to night company has generated more no of hot leads so we concluded that
#We can show ads to people in above given time slots as more no of people use their mobile phones in evening and night
#so this time is preferrable.
#The maximum cost we used to show ad is in time slot of 7:30 pm to 9:00 pm where we generate 4 no of hot leads
#In each no of time slot
# In the time slots company has get more no of impressions, clicks,cold lead,warm lead,hot lead.

In [52]:
#There are 18 no of non preferred time slots and that company dosent get hot lead

In [53]:
#In time slots where company dosent get hot lead company spent 756 rs 
#In reamaning time slots where company got hot leads company spent 19301 rs
#So total cost spent by  company on every time slot is 20054 rs
#Total percentage of cost spend to generate hot leads is 96.24%

In [54]:
#We suggest we can reduce the cost by 3.76% not spending in the 1:00 am to 10:00 am time slots